# -*- coding: utf-8 -*-
"""DTW (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mn-6iA-n16TdHrfEZcTV7lqY-xkCT9X-
"""

# Install necessary libraries
!pip install dtaidistance
!pip install fastdtw

# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from dtaidistance import dtw
from google.colab import files

# Step 1: Upload data file
uploaded = files.upload()
df = pd.read_excel(next(iter(uploaded)), header=None)

# Step 2: Calculate the average for the left and right foot data per row
left_foot_avg = df.iloc[:, :16].mean(axis=1)  # Average of the first 16 columns (Left Foot)
right_foot_avg = df.iloc[:, 16:].mean(axis=1)  # Average of the next 16 columns (Right Foot)

# Step 3: Compute the DTW distance and best path
distance, paths = dtw.warping_paths(left_foot_avg, right_foot_avg)
best_path = dtw.best_path(paths)

# Display similarity score
similarity_score = 1 - (distance / (len(left_foot_avg) + len(right_foot_avg)))
print(f"DTW Similarity Score: {similarity_score:.2f}")

# Step 4: Plotting
plt.figure(figsize=(14, 10))

# Plot the original time series
plt.subplot(2, 2, 1)
plt.plot(left_foot_avg, label='Left Foot', color='blue', linewidth=0.8, marker='o', markersize=2)
plt.plot(right_foot_avg, label='Right Foot', linestyle='--', color='orange', linewidth=0.8, marker='x', markersize=2)
plt.title('Original Time Series')
plt.xlabel('Time (s)')
plt.ylabel('Average Pressure')
plt.legend()

# Plot the DTW best path
plt.subplot(2, 2, 2)
plt.plot(np.array(best_path)[:, 0], np.array(best_path)[:, 1], 'green', marker='o', linestyle='-', linewidth=0.6, markersize=3)
plt.title('Shortest Path (Best Path)')
plt.xlabel('Left Foot')
plt.ylabel('Right Foot')
plt.grid(True)

# Plot point-to-point comparison
plt.subplot(2, 1, 2)
plt.plot(left_foot_avg, label='Left Foot', color='blue', linewidth=0.6, marker='o', markersize=2)
plt.plot(right_foot_avg, label='Right Foot', color='orange', linestyle='--', linewidth=0.6, marker='x', markersize=2)
for a, b in best_path:
    plt.plot([a, b], [left_foot_avg[a], right_foot_avg[b]], color='grey', linestyle='-', linewidth=0.4, alpha=0.3)
plt.title('Point-to-Point Comparison After DTW Alignment')
plt.xlabel('Time (s)')
plt.ylabel('Pressure (kpa) ')
plt.legend()

plt.tight_layout()
plt.show()

# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from dtaidistance import dtw
from google.colab import files

# Step 1: Upload data file
uploaded = files.upload()  # Prompt for Excel file upload

# Read the uploaded Excel file (assumes no header, adjust if necessary)
df = pd.read_excel(next(iter(uploaded)), header=None)

# Step 2: Calculate the average for the left and right foot data per row
left_foot_avg = df.iloc[:, :16].mean(axis=1)  # Average of the first 16 columns (Left Foot)
right_foot_avg = df.iloc[:, 16:].mean(axis=1) # Average of the next 16 columns (Right Foot)

# Step 3: Compute the DTW distance and alignment path
distance, paths = dtw.warping_paths(left_foot_avg, right_foot_avg)
best_path = dtw.best_path(paths)

# Display unnormalized DTW distance
print(f"DTW Distance: {distance:.2f}")

# Step 4: Plot the point-to-point comparison after DTW alignment
plt.figure(figsize=(12, 8))

# Original Time Series Plot
plt.subplot(2, 2, 1)
plt.plot(left_foot_avg, label='Left Foot', color='blue', linewidth=0.5, marker='o', markersize=1)
plt.plot(right_foot_avg, label='Right Foot', linestyle='--', color='orange', linewidth=0.5, marker='x', markersize=1)
plt.title('Original Time Series')
plt.xlabel('Time (s)')
plt.ylabel('Average Pressure')
plt.legend()

# Shortest Path Plot (Cost Matrix with the path)
plt.subplot(2, 2, 2)
plt.plot(np.array(best_path)[:, 0], np.array(best_path)[:, 1], 'green', marker='o', linestyle='-', linewidth=0.5, markersize=1)
plt.title('Shortest Path (Best Path)')
plt.xlabel('Left Foot')
plt.ylabel('Right Foot')
plt.grid(True)

# Point-to-Point Comparison Plot
plt.subplot(2, 1, 2)
plt.plot(left_foot_avg, label='Left Foot', color='blue', marker='o', linewidth=0.4, markersize=1.5)
plt.plot(right_foot_avg, label='Right Foot', color='orange', marker='x', linestyle='--', linewidth=0.4, markersize=1.5)
for a, b in best_path:
    plt.plot([a, b], [left_foot_avg[a], right_foot_avg[b]], color='grey', linestyle='-', linewidth=0.3, alpha=0.25)
plt.title('Point-to-Point Comparison After DTW Alignment')
plt.xlabel('Time (s)')
plt.ylabel('Pressure (kpa)')
plt.legend()

plt.tight_layout()
plt.show()